#!/usr/bin/env bash
# Bash script to Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
echo "School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
